# Generated by Django 4.2 on 2026-09-18 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IzinKeluar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('kategori', models.CharField(choices=[('dinas', 'Dinas Luar'), ('pribadi', 'Urusan Pribadi'), ('sakit', 'Sakit / Berobat')], default='dinas', max_length=20)),
                ('keperluan', models.TextField()),
                ('jam_keluar_awal', models.TimeField()),
                ('jam_kembali_awal', models.TimeField()),
                ('jam_keluar', models.TimeField()),
                ('jam_kembali', models.TimeField()),
                ('jam_kembali_aktual', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('berjalan', 'Sedang di Luar'), ('selesai', 'Sudah Kembali'), ('dibatalkan', 'Dibatalkan')], default='berjalan', max_length=20)),
                ('is_adjusted', models.BooleanField(default=False)),
                ('catatan_kembali', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='izin_keluar_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Izin Meninggalkan Tempat Kerja',
                'verbose_name_plural': 'Daftar Izin Meninggalkan Tempat Kerja',
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IzinKeluarLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jam_keluar_sebelum', models.TimeField()),
                ('jam_kembali_sebelum', models.TimeField()),
                ('jam_keluar_sesudah', models.TimeField()),
                ('jam_kembali_sesudah', models.TimeField()),
                ('alasan_penyesuaian', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('izin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='sdm.izinkeluar')),
            ],
            options={
                'verbose_name': 'Log Penyesuaian Izin Keluar',
                'verbose_name_plural': 'Log Penyesuaian Izin Keluar',
                'ordering': ['-created_at'],
            },
        ),
    ]
