# Generated by Django 4.2 on 2026-10-08 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sdm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='izinkeluar',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='izinkeluar',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='izin_keluar_disetujui', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='izinkeluar',
            name='catatan_approval',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='izinkeluar',
            name='status',
            field=models.CharField(choices=[('menunggu_approval', 'Menunggu Persetujuan'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak'), ('berjalan', 'Sedang di Luar'), ('selesai', 'Sudah Kembali'), ('dibatalkan', 'Dibatalkan')], default='menunggu_approval', max_length=20),
        ),
    ]
