# Generated by Django 4.2 on 2026-08-20 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Pekerjaan')),
                ('jam_mulai', models.TimeField(verbose_name='Jam Mulai')),
                ('jam_selesai', models.TimeField(verbose_name='Jam Selesai')),
                ('deskripsi', models.TextField(verbose_name='Uraian / Deskripsi Pekerjaan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logbooks', to=settings.AUTH_USER_MODEL, verbose_name='Pegawai / Pengguna')),
            ],
            options={
                'verbose_name': 'Logbook Harian',
                'verbose_name_plural': 'Logbook Harian',
                'db_table': 'logbook_harian',
                'ordering': ['-tanggal', '-jam_mulai', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='logbook',
            index=models.Index(fields=['-tanggal', 'user'], name='logbook_har_tanggal_7d5c52_idx'),
        ),
        migrations.AddIndex(
            model_name='logbook',
            index=models.Index(fields=['tanggal'], name='logbook_har_tanggal_9dc341_idx'),
        ),
    ]
