# Generated by Django 4.2 on 2026-08-26 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_task', models.CharField(editable=False, max_length=25, unique=True)),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('on_progress', 'On Progress'), ('on_hold', 'On Hold'), ('done', 'Done')], default='on_progress', max_length=15)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_menit_kerja', models.IntegerField(default=0)),
                ('total_menit_lembur', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'logbook_task',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SesiKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mulai', models.DateTimeField()),
                ('selesai', models.DateTimeField(blank=True, null=True)),
                ('durasi_kerja', models.IntegerField(default=0, help_text='Menit dalam jam kerja')),
                ('durasi_lembur', models.IntegerField(default=0, help_text='Menit di luar jam kerja')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesi_list', to='logbook.task')),
            ],
            options={
                'db_table': 'logbook_sesi_kerja',
                'ordering': ['mulai'],
            },
        ),
    ]
