# Generated by Django 4.2 on 2026-09-07 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logbook', '0002_task_sesikerja'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='catatan_verifikasi',
            field=models.TextField(blank=True, verbose_name='Catatan Verifikasi'),
        ),
        migrations.AddField(
            model_name='logbook',
            name='nama_aktivitas',
            field=models.CharField(blank=True, max_length=300, verbose_name='Nama Aktivitas'),
        ),
        migrations.AddField(
            model_name='logbook',
            name='nilai_output',
            field=models.IntegerField(default=0, verbose_name='Nilai Output'),
        ),
        migrations.AddField(
            model_name='logbook',
            name='satuan_output',
            field=models.CharField(blank=True, max_length=100, verbose_name='Satuan Output'),
        ),
        migrations.AddField(
            model_name='logbook',
            name='status',
            field=models.CharField(choices=[('perlu_verifikasi', 'Perlu Verifikasi'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='perlu_verifikasi', max_length=20),
        ),
        migrations.AddField(
            model_name='logbook',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logbook',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_logbooks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UraianTugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.TextField(verbose_name='Uraian Tugas / Job Description')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uraian_tugas_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'logbook_uraian_tugas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='logbook',
            name='uraian_tugas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logbooks', to='logbook.uraiantugas'),
        ),
    ]
