# Generated by Django 4.2 on 2026-09-07 12:08

from django.db import migrations


def update_existing_logbook_status(apps, schema_editor):
    Logbook = apps.get_model('logbook', 'Logbook')
    Logbook.objects.update(status='disetujui')

class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0003_logbook_catatan_verifikasi_logbook_nama_aktivitas_and_more'),
    ]

    operations = [
        migrations.RunPython(update_existing_logbook_status, reverse_code=migrations.RunPython.noop),
    ]
