# Generated by Django 4.2 on 2026-09-18 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0004_update_status_disetujui'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='durasi_kerja',
            field=models.IntegerField(default=0, verbose_name='Durasi Jam Kerja (menit)'),
        ),
        migrations.AddField(
            model_name='logbook',
            name='durasi_lembur',
            field=models.IntegerField(default=0, verbose_name='Durasi Lembur (menit)'),
        ),
        migrations.AddField(
            model_name='logbook',
            name='metode_input',
            field=models.CharField(choices=[('manual', 'Manual'), ('live_track', 'Live Track')], default='manual', max_length=20, verbose_name='Metode Pencatatan'),
        ),
        migrations.AddField(
            model_name='logbook',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logbook_entries', to='logbook.task', verbose_name='Referensi Task Live Track'),
        ),
        migrations.AddField(
            model_name='task',
            name='nilai_output',
            field=models.IntegerField(default=0, verbose_name='Nilai Output'),
        ),
        migrations.AddField(
            model_name='task',
            name='satuan_output',
            field=models.CharField(blank=True, max_length=100, verbose_name='Satuan Output'),
        ),
        migrations.AddField(
            model_name='task',
            name='uraian_tugas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='logbook.uraiantugas', verbose_name='Uraian Tugas'),
        ),
    ]
