# Generated by Django 4.2 on 2026-09-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0005_logbook_durasi_kerja_logbook_durasi_lembur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Siap Mulai'), ('on_progress', 'On Progress'), ('on_hold', 'On Hold'), ('done', 'Done')], default='pending', max_length=15),
        ),
    ]
