# Generated by Django 4.2 on 2026-03-11 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_akun', models.CharField(max_length=20, unique=True)),
                ('nama_akun', models.CharField(max_length=100)),
                ('kategori', models.CharField(choices=[('kas', 'Kas'), ('bank', 'Bank'), ('piutang', 'Piutang'), ('hutang', 'Hutang'), ('pendapatan', 'Pendapatan'), ('beban', 'Beban'), ('lainnya', 'Lainnya')], default='lainnya', max_length=20)),
                ('is_kas_setara', models.BooleanField(default=False, help_text='Centang jika akun ini termasuk Kas & Setara Kas')),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Akun',
                'verbose_name_plural': 'Daftar Akun',
                'ordering': ['kode_akun'],
            },
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('nomor_referensi', models.CharField(blank=True, max_length=50, null=True)),
                ('keterangan', models.TextField()),
                ('jenis', models.CharField(choices=[('masuk', 'Kas Masuk'), ('keluar', 'Kas Keluar')], max_length=10)),
                ('kategori_arus', models.CharField(choices=[('operasi', 'Aktivitas Operasi'), ('investasi', 'Aktivitas Investasi & Kejadian Luar Biasa'), ('keuangan', 'Aktivitas Keuangan'), ('tidak_diklasifikasi', 'Tidak Diklasifikasi')], max_length=25)),
                ('sub_kategori', models.CharField(choices=[('tagihan_muka_pelanggan', 'Tagihan Muka yang Diterima dari Pelanggan'), ('kas_masuk_operasi', 'Uang Kas yang Diterima dari Kegiatan Operasi'), ('tagihan_muka_pemasok', 'Tagihan Muka yang Dibuat untuk Pemasok'), ('kas_keluar_operasi', 'Uang Kas yang Dibayar untuk Kegiatan Operasi'), ('kas_masuk_investasi', 'Kas Masuk Investasi'), ('kas_keluar_investasi', 'Kas Keluar Investasi'), ('kas_masuk_keuangan', 'Kas Masuk Keuangan'), ('kas_keluar_keuangan', 'Kas Keluar Keuangan'), ('kas_masuk_lainnya', 'Kas Masuk Lainnya'), ('kas_keluar_lainnya', 'Kas Keluar Lainnya')], max_length=30)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaksi', to='keuangan.akun')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaksi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaksi',
                'verbose_name_plural': 'Daftar Transaksi',
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
    ]
