# Generated by Django 4.2 on 2026-03-12 01:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='akun',
            name='kategori',
        ),
        migrations.AddField(
            model_name='akun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='akun',
            name='saldo_normal',
            field=models.CharField(choices=[('debit', 'Debit'), ('kredit', 'Kredit')], default='debit', max_length=10),
        ),
        migrations.AddField(
            model_name='akun',
            name='tipe',
            field=models.CharField(choices=[('aset_lancar', 'Aset Lancar'), ('aset_tetap', 'Aset Tetap'), ('aset_lainnya', 'Aset Lainnya'), ('kewajiban_lancar', 'Kewajiban Lancar'), ('kewajiban_jangka_panjang', 'Kewajiban Jangka Panjang'), ('ekuitas', 'Ekuitas'), ('pendapatan', 'Pendapatan'), ('harga_pokok', 'Harga Pokok Penjualan'), ('beban_operasional', 'Beban Operasional'), ('beban_lainnya', 'Beban Lainnya'), ('pendapatan_lainnya', 'Pendapatan Lainnya')], default='aset_lancar', max_length=30),
        ),
    ]
