# Generated by Django 4.2 on 2026-03-12 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keuangan', '0002_remove_akun_kategori_akun_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jurnal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_jurnal', models.CharField(max_length=50, unique=True)),
                ('tanggal', models.DateField()),
                ('keterangan', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Diposting')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jurnal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jurnal',
                'verbose_name_plural': 'Entri Jurnal',
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='akun',
            name='is_kas_setara',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='JurnalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.CharField(blank=True, max_length=200)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('kredit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jurnal_items', to='keuangan.akun')),
                ('jurnal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='keuangan.jurnal')),
            ],
            options={
                'verbose_name': 'Item Jurnal',
                'verbose_name_plural': 'Item Jurnal',
            },
        ),
    ]
