# Generated by Django 4.2 on 2026-03-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0003_jurnal_alter_akun_is_kas_setara_jurnalitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=150)),
                ('tipe', models.CharField(choices=[('umum', 'Umum'), ('bpjs', 'BPJS'), ('asuransi', 'Asuransi Swasta'), ('perusahaan', 'Perusahaan')], default='umum', max_length=20)),
                ('telepon', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('no_kontrak', models.CharField(blank=True, max_length=50, null=True)),
                ('batas_kredit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pelanggan',
                'verbose_name_plural': 'Daftar Pelanggan',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Pemasok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=150)),
                ('tipe', models.CharField(choices=[('obat', 'Supplier Obat'), ('alkes', 'Supplier Alkes'), ('jasa', 'Jasa'), ('umum', 'Umum')], default='umum', max_length=20)),
                ('telepon', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('npwp', models.CharField(blank=True, max_length=30, null=True)),
                ('no_rekening', models.CharField(blank=True, max_length=50, null=True)),
                ('bank', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pemasok',
                'verbose_name_plural': 'Daftar Pemasok',
                'ordering': ['nama'],
            },
        ),
        migrations.AlterModelOptions(
            name='jurnalitem',
            options={},
        ),
    ]
