# Generated by Django 4.2 on 2026-03-12 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keuangan', '0004_pelanggan_pemasok_alter_jurnalitem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faktur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_faktur', models.CharField(max_length=50, unique=True)),
                ('tanggal', models.DateField()),
                ('jatuh_tempo', models.DateField()),
                ('keterangan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('dikirim', 'Dikirim'), ('sebagian', 'Dibayar Sebagian'), ('lunas', 'Lunas'), ('batal', 'Dibatalkan')], default='draft', max_length=10)),
                ('total_tagihan', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_dibayar', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faktur', to=settings.AUTH_USER_MODEL)),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faktur', to='keuangan.pelanggan')),
            ],
            options={
                'verbose_name': 'Faktur',
                'verbose_name_plural': 'Daftar Faktur',
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PembayaranFaktur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=15)),
                ('metode', models.CharField(choices=[('tunai', 'Tunai'), ('transfer', 'Transfer Bank'), ('bpjs', 'BPJS'), ('asuransi', 'Asuransi')], default='tunai', max_length=20)),
                ('keterangan', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pembayaran_faktur', to='keuangan.akun')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pembayaran_faktur', to=settings.AUTH_USER_MODEL)),
                ('faktur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pembayaran', to='keuangan.faktur')),
            ],
            options={
                'verbose_name': 'Pembayaran Faktur',
                'verbose_name_plural': 'Pembayaran Faktur',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='FakturItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.CharField(max_length=200)),
                ('kuantitas', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('faktur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='keuangan.faktur')),
            ],
        ),
    ]
