# Generated by Django 4.2 on 2026-03-13 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0006_tagihan_tagihanitem_pembayarantagihan'),
    ]

    operations = [
        migrations.CreateModel(
            name='RekeningBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_rekening', models.CharField(help_text='Nama pemilik/alias rekening', max_length=150)),
                ('bank', models.CharField(choices=[('bri', 'Bank BRI'), ('bsi', 'Bank BSI'), ('lainnya', 'Bank Lainnya')], max_length=20)),
                ('nama_bank', models.CharField(blank=True, help_text='Diisi jika bank = lainnya', max_length=100)),
                ('nomor_rekening', models.CharField(max_length=50, unique=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('keterangan', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rekening_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rekening Bank',
                'verbose_name_plural': 'Daftar Rekening Bank',
                'ordering': ['bank', 'nama_rekening'],
            },
        ),
        migrations.CreateModel(
            name='RiwayatSaldoRekening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_sebelum', models.DecimalField(decimal_places=2, max_digits=18)),
                ('saldo_sesudah', models.DecimalField(decimal_places=2, max_digits=18)),
                ('selisih', models.DecimalField(decimal_places=2, max_digits=18)),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rekening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat', to='keuangan.rekeningbank')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riwayat_rekening', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Riwayat Saldo Rekening',
                'ordering': ['-created_at'],
            },
        ),
    ]
