# Generated by Django 4.2 on 2026-04-07 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import keuangan.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keuangan', '0009_rekeningbank_riwayatsaldorekening'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kendaraan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plat_nomor', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(help_text='Contoh: Avanza Putih, Ambulans 1', max_length=100)),
                ('jenis', models.CharField(choices=[('mobil', 'Mobil'), ('motor', 'Motor'), ('ambulans', 'Ambulans'), ('pickup', 'Pickup'), ('bus', 'Bus'), ('lainnya', 'Lainnya')], default='mobil', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kendaraan',
                'verbose_name_plural': 'Daftar Kendaraan',
                'ordering': ['jenis', 'nama'],
            },
        ),
        migrations.AlterField(
            model_name='rekeningbank',
            name='nama_bank',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='rekeningbank',
            name='nama_rekening',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='SaldoPettyCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saldo_pc_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saldo Petty Cash',
            },
        ),
        migrations.CreateModel(
            name='RiwayatSaldoPettyCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pengaju', models.CharField(blank=True, max_length=150)),
                ('unit_pengaju', models.CharField(blank=True, max_length=150)),
                ('jenis', models.CharField(choices=[('penambahan', 'Penambahan'), ('pengurangan', 'Pengurangan')], max_length=20)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo_sebelum', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo_sesudah', models.DecimalField(decimal_places=2, max_digits=15)),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riwayat_saldo_pc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Riwayat Saldo Petty Cash',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_reimbursement', models.CharField(editable=False, max_length=20, unique=True)),
                ('tanggal', models.DateField()),
                ('keperluan', models.TextField()),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('keterangan', models.TextField(blank=True)),
                ('berkas', models.FileField(upload_to=keuangan.models.berkas_rb_path)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak'), ('dicairkan', 'Dicairkan')], default='pending', max_length=20)),
                ('catatan_tolak', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_pengajuan', to=settings.AUTH_USER_MODEL)),
                ('dicairkan_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_dicairkan', to=settings.AUTH_USER_MODEL)),
                ('disetujui_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_disetujui', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reimbursement',
                'verbose_name_plural': 'Reimbursement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PettyCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_pengajuan', models.CharField(editable=False, max_length=20, unique=True)),
                ('tanggal', models.DateField()),
                ('keperluan', models.TextField()),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('keterangan', models.TextField(blank=True)),
                ('berkas', models.FileField(blank=True, null=True, upload_to=keuangan.models.berkas_pc_path)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak'), ('dicairkan', 'Dicairkan'), ('dilaporkan', 'Dilaporkan'), ('menunggu_pengembalian', 'Menunggu Pengembalian'), ('selesai', 'Selesai')], default='pending', max_length=30)),
                ('catatan_tolak', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_pengajuan', to=settings.AUTH_USER_MODEL)),
                ('dicairkan_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_dicairkan', to=settings.AUTH_USER_MODEL)),
                ('disetujui_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_disetujui', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Petty Cash',
                'verbose_name_plural': 'Petty Cash',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PengajuanPenambahanSaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_pengajuan', models.CharField(editable=False, max_length=25, unique=True)),
                ('tanggal', models.DateField()),
                ('alasan', models.TextField()),
                ('nominal_diajukan', models.DecimalField(blank=True, decimal_places=2, help_text='Diisi direktur saat menyetujui', max_digits=15, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='pending', max_length=20)),
                ('catatan_tolak', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengajuan_penambahan_saldo', to=settings.AUTH_USER_MODEL)),
                ('diproses_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proses_penambahan_saldo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pengajuan Penambahan Saldo',
                'verbose_name_plural': 'Pengajuan Penambahan Saldo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogPerjalanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jam_berangkat', models.TimeField()),
                ('jam_kembali', models.TimeField(blank=True, null=True)),
                ('tujuan', models.CharField(max_length=255)),
                ('km_awal', models.PositiveIntegerField(help_text='KM odometer saat berangkat')),
                ('km_akhir', models.PositiveIntegerField(blank=True, help_text='KM odometer saat kembali', null=True)),
                ('jarak_km', models.PositiveIntegerField(blank=True, help_text='Otomatis dihitung', null=True)),
                ('penumpang', models.CharField(blank=True, help_text='Nama penumpang jika ada', max_length=255)),
                ('keterangan', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=keuangan.models.foto_perjalanan_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_perjalanan', to=settings.AUTH_USER_MODEL)),
                ('kendaraan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log_perjalanan', to='keuangan.kendaraan')),
            ],
            options={
                'verbose_name': 'Log Perjalanan',
                'verbose_name_plural': 'Log Perjalanan',
                'ordering': ['-tanggal', '-jam_berangkat'],
            },
        ),
        migrations.CreateModel(
            name='LogMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('servis_rutin', 'Servis Rutin'), ('ganti_oli', 'Ganti Oli'), ('ban', 'Ganti / Tambal Ban'), ('aki', 'Ganti Aki'), ('rem', 'Perbaikan Rem'), ('ac', 'Servis AC'), ('body', 'Perbaikan Body'), ('lainnya', 'Lainnya')], max_length=30)),
                ('tanggal', models.DateField()),
                ('biaya', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deskripsi', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dilaporkan_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_maintenance', to=settings.AUTH_USER_MODEL)),
                ('kendaraan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log_maintenance', to='keuangan.kendaraan')),
            ],
            options={
                'verbose_name': 'Log Maintenance',
                'verbose_name_plural': 'Log Maintenance',
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogBBM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('total_biaya', models.DecimalField(decimal_places=2, max_digits=12)),
                ('km_saat_isi', models.PositiveIntegerField(blank=True, help_text='KM odometer saat isi BBM', null=True)),
                ('keterangan', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=keuangan.models.foto_bbm_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_bbm', to=settings.AUTH_USER_MODEL)),
                ('kendaraan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log_bbm', to='keuangan.kendaraan')),
            ],
            options={
                'verbose_name': 'Log BBM',
                'verbose_name_plural': 'Log BBM',
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LaporanPenggunaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_laporan', models.DateField()),
                ('nominal_digunakan', models.DecimalField(decimal_places=2, max_digits=15)),
                ('selisih', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('rincian', models.TextField()),
                ('nota', models.FileField(blank=True, null=True, upload_to=keuangan.models.nota_pc_path)),
                ('pengembalian_selesai', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dikonfirmasi_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='konfirmasi_laporan', to=settings.AUTH_USER_MODEL)),
                ('petty_cash', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laporan', to='keuangan.pettycash')),
            ],
            options={
                'verbose_name': 'Laporan Penggunaan',
                'verbose_name_plural': 'Laporan Penggunaan',
            },
        ),
    ]
