# Generated by Django 4.2 on 2026-04-07 05:45

from django.db import migrations, models
import keuangan.models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0010_kendaraan_alter_rekeningbank_nama_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmaintenance',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=keuangan.models.foto_maintenance_path),
        ),
    ]
