# Generated by Django 4.2 on 2026-04-10 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keuangan', '0011_logmaintenance_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='IzinPerjalanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_izin', models.CharField(editable=False, max_length=20, unique=True)),
                ('tanggal_berangkat', models.DateField(help_text='Tanggal keberangkatan')),
                ('tanggal_kembali', models.DateField(help_text='Tanggal kembali')),
                ('tujuan', models.CharField(help_text='Tujuan perjalanan', max_length=255)),
                ('keterangan', models.TextField(blank=True, help_text='Alasan/keperluan perjalanan')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='pending', max_length=20)),
                ('catatan_tolak', models.TextField(blank=True, help_text='Catatan jika ditolak')),
                ('disetujui_pada', models.DateTimeField(blank=True, null=True)),
                ('ditolak_pada', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='izin_created', to=settings.AUTH_USER_MODEL)),
                ('disetujui_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='izin_disetujui', to=settings.AUTH_USER_MODEL)),
                ('ditolak_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='izin_ditolak', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='izin_perjalanan', to=settings.AUTH_USER_MODEL)),
                ('kendaraan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='izin_perjalanan', to='keuangan.kendaraan')),
            ],
            options={
                'verbose_name': 'Izin Perjalanan',
                'verbose_name_plural': 'Daftar Izin Perjalanan',
                'ordering': ['-created_at'],
                'unique_together': {('driver', 'tanggal_berangkat', 'kendaraan')},
            },
        ),
        migrations.AddField(
            model_name='logperjalanan',
            name='izin',
            field=models.ForeignKey(blank=True, help_text='Tautkan ke izin yang disetujui', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_perjalanan', to='keuangan.izinperjalanan'),
        ),
    ]
