# Generated by Django 4.2 on 2026-04-10 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0012_izinperjalanan_logperjalanan_izin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izinperjalanan',
            name='status',
            field=models.CharField(choices=[('pending', 'Diajukan'), ('disetujui', 'Disetujui'), ('log_diisi', 'Isi Log Perjalanan'), ('selesai', 'Selesai'), ('ditolak', 'Ditolak')], default='pending', max_length=20),
        ),
    ]
