# Generated by Django 4.2 on 2026-04-11 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keuangan', '0013_alter_izinperjalanan_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logperjalanan',
            name='izin',
        ),
        migrations.AddField(
            model_name='logperjalanan',
            name='catatan_tolak',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='logperjalanan',
            name='disetujui_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_log_perjalanan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logperjalanan',
            name='no_perjalanan',
            field=models.CharField(blank=True, editable=False, max_length=25, unique=True),
        ),
        migrations.AddField(
            model_name='logperjalanan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak'), ('selesai', 'Selesai')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='IzinPerjalanan',
        ),
    ]
