import driver.models
# Generated by Django 4.2 on 2026-04-11 03:46

from django.db import migrations, models
import django.db.models.deletion
import keuangan.models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0014_remove_logperjalanan_izin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logperjalanan',
            name='foto',
        ),
        migrations.AlterField(
            model_name='logperjalanan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak'), ('dilaporkan', 'Dilaporkan'), ('selesai', 'Selesai')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='LaporanPerjalanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_laporan', models.DateField()),
                ('deskripsi', models.TextField(help_text='Deskripsi perjalanan dan aktivitas')),
                ('tujuan_tercapai', models.BooleanField(default=True)),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('log_perjalanan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laporan', to='keuangan.logperjalanan')),
            ],
            options={
                'verbose_name': 'Laporan Perjalanan',
                'verbose_name_plural': 'Laporan Perjalanan',
            },
        ),
        migrations.CreateModel(
            name='FotoLaporanPerjalanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to=driver.models.foto_laporan_perjalanan_path)),
                ('urutan', models.PositiveIntegerField(default=1, help_text='Urutan foto')),
                ('keterangan', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto', to='keuangan.laporanperjalanan')),
            ],
            options={
                'verbose_name': 'Foto Laporan Perjalanan',
                'verbose_name_plural': 'Foto Laporan Perjalanan',
                'ordering': ['urutan', 'created_at'],
            },
        ),
    ]
