# Generated by Django 4.2 on 2026-04-29 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keuangan', '0015_remove_logperjalanan_foto_alter_logperjalanan_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('action', 'Action'), ('login', 'Login')], max_length=20)),
                ('entity_type', models.CharField(max_length=30)),
                ('entity_id', models.IntegerField(default=0)),
                ('entity_display', models.CharField(blank=True, max_length=255)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('status', models.CharField(default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['entity_type', 'entity_id'], name='keuangan_au_entity__f2af1e_idx'),
                    models.Index(fields=['user', '-created_at'], name='keuangan_au_user_id_bcbc70_idx'),
                    models.Index(fields=['action', '-created_at'], name='keuangan_au_action_191ccc_idx'),
                    models.Index(fields=['-created_at'], name='keuangan_au_created_b5330a_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=120)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['idempotency_key', 'user'], name='keuangan_id_idempot_f20424_idx'),
                    models.Index(fields=['-created_at'], name='keuangan_id_created_80e4ee_idx'),
                ],
            },
        ),
    ]
