# Generated by Django 4.2 on 2026-04-29 23:54

from django.db import migrations, models
import django.db.models.deletion
import keuangan.models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0019_rename_keuangan_auditlog_idx_entity_keuangan_au_entity__f2af1e_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoReimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to=keuangan.models.foto_reimbursement_path)),
                ('urutan', models.PositiveIntegerField(default=1, help_text='Urutan foto')),
                ('keterangan', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reimbursement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_list', to='keuangan.reimbursement')),
            ],
            options={
                'verbose_name': 'Foto Reimbursement',
                'verbose_name_plural': 'Foto Reimbursement',
                'ordering': ['urutan', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FotoPettyCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to=keuangan.models.foto_petty_cash_path)),
                ('urutan', models.PositiveIntegerField(default=1, help_text='Urutan foto')),
                ('keterangan', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('petty_cash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_list', to='keuangan.pettycash')),
            ],
            options={
                'verbose_name': 'Foto Petty Cash',
                'verbose_name_plural': 'Foto Petty Cash',
                'ordering': ['urutan', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FotoLaporanPenggunaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to=keuangan.models.foto_laporan_penggunaan_path)),
                ('urutan', models.PositiveIntegerField(default=1, help_text='Urutan foto')),
                ('keterangan', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_list', to='keuangan.laporanpenggunaan')),
            ],
            options={
                'verbose_name': 'Foto Laporan Penggunaan',
                'verbose_name_plural': 'Foto Laporan Penggunaan',
                'ordering': ['urutan', 'created_at'],
            },
        ),
    ]
