# Generated by Django 4.2 on 2026-05-15 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keuangan', '0020_fotoreimbursement_fotopettycash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITRepairRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('requester_name', models.CharField(blank=True, max_length=120)),
                ('unit', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('category', models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software'), ('network', 'Jaringan'), ('printer', 'Printer'), ('account', 'Akun / Akses'), ('simak', 'SIMAK'), ('other', 'Lainnya')], default='other', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Rendah'), ('normal', 'Normal'), ('high', 'Tinggi'), ('urgent', 'Darurat')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Baru'), ('in_progress', 'Diproses'), ('waiting', 'Menunggu'), ('done', 'Selesai'), ('cancelled', 'Dibatalkan')], default='open', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('resolution', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_repair_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ITRemoteAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=160)),
                ('user_owner', models.CharField(blank=True, max_length=120)),
                ('unit', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('anydesk_id', models.CharField(blank=True, max_length=80)),
                ('rustdesk_id', models.CharField(blank=True, max_length=80)),
                ('access_password', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('inactive', 'Nonaktif'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_remote_access_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['device_name'],
            },
        ),
        migrations.CreateModel(
            name='ITCredentialNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('website', 'Website'), ('server', 'Server'), ('database', 'Database'), ('email', 'Email'), ('device', 'Perangkat'), ('vendor', 'Vendor'), ('other', 'Lainnya')], default='website', max_length=30)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('username', models.CharField(blank=True, max_length=180)),
                ('password', models.TextField(blank=True)),
                ('owner', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_credential_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ITBackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('database', 'Database'), ('media', 'Media Upload'), ('full', 'Database + Media'), ('config', 'Konfigurasi'), ('other', 'Lainnya')], default='database', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Terjadwal'), ('running', 'Berjalan'), ('success', 'Berhasil'), ('failed', 'Gagal'), ('verified', 'Terverifikasi')], default='success', max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('storage_path', models.CharField(blank=True, max_length=500)),
                ('file_size_mb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_backup_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='itrepairrequest',
            index=models.Index(fields=['status', 'priority'], name='it_ticket_status_idx'),
        ),
        migrations.AddIndex(
            model_name='itrepairrequest',
            index=models.Index(fields=['requested_at'], name='it_ticket_requested_idx'),
        ),
        migrations.AddIndex(
            model_name='itremoteaccess',
            index=models.Index(fields=['status', 'device_name'], name='it_remote_status_idx'),
        ),
        migrations.AddIndex(
            model_name='itremoteaccess',
            index=models.Index(fields=['unit'], name='it_remote_unit_idx'),
        ),
        migrations.AddIndex(
            model_name='itcredentialnote',
            index=models.Index(fields=['category', 'is_active'], name='it_credential_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='itcredentialnote',
            index=models.Index(fields=['name'], name='it_credential_name_idx'),
        ),
        migrations.AddIndex(
            model_name='itbackuprecord',
            index=models.Index(fields=['status', '-created_at'], name='it_backup_status_idx'),
        ),
        migrations.AddIndex(
            model_name='itbackuprecord',
            index=models.Index(fields=['backup_type', '-created_at'], name='it_backup_type_idx'),
        ),
    ]
