# Generated by Django 4.2 on 2026-05-15 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import keuangan.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keuangan', '0021_itrepairrequest_itremoteaccess_itcredentialnote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itrepairrequest',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='itrepairrequest',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=keuangan.models.foto_it_repair_path),
        ),
        migrations.AddField(
            model_name='itrepairrequest',
            name='requester_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_reported_repairs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itrepairrequest',
            name='sparepart',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
