# Generated by Django 4.2 on 2026-05-15 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0022_itrepairrequest_cost_itrepairrequest_foto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itrepairrequest',
            name='location',
        ),
    ]
