# Generated by Django 4.2 on 2026-05-17 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keuangan', '0023_remove_itrepairrequest_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('service_type', models.CharField(choices=[('domain', 'Domain'), ('hosting', 'Hosting'), ('ssl', 'SSL'), ('internet', 'Internet'), ('software', 'Software / Lisensi'), ('vendor', 'Vendor / Support'), ('other', 'Lainnya')], default='software', max_length=30)),
                ('vendor', models.CharField(blank=True, max_length=160)),
                ('account_ref', models.CharField(blank=True, max_length=180)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('pic', models.CharField(blank=True, max_length=120)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Bulanan'), ('quarterly', 'Triwulan'), ('semester', 'Semester'), ('yearly', 'Tahunan'), ('one_time', 'Sekali Bayar')], default='yearly', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('expiring', 'Hampir Habis'), ('expired', 'Expired'), ('cancelled', 'Dibatalkan')], default='active', max_length=20)),
                ('reminder_days', models.PositiveIntegerField(default=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['end_date', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='itsubscription',
            index=models.Index(fields=['status', 'end_date'], name='it_sub_status_end_idx'),
        ),
        migrations.AddIndex(
            model_name='itsubscription',
            index=models.Index(fields=['service_type', 'end_date'], name='it_sub_type_end_idx'),
        ),
    ]
