# Generated by Django 4.2 on 2026-05-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0025_announcement_announcementread_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='audience',
            field=models.CharField(default='all', max_length=180),
        ),
    ]
