# Generated by Django 4.2 on 2026-05-29 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import keuangan.models


def seed_inventory_options(apps, schema_editor):
    InventoryOption = apps.get_model('keuangan', 'InventoryOption')
    defaults = {
        'unit': ['IGD', 'Rawat Inap', 'Radiologi', 'Laboratorium', 'Farmasi', 'Administrasi', 'IT', 'Driver'],
        'category': ['Elektronik', 'Medis', 'Furniture', 'Kendaraan', 'Komputer & Jaringan', 'Bangunan', 'Lainnya'],
        'condition': ['Layak Pakai', 'Perlu Perbaikan', 'Rusak Ringan', 'Rusak Berat', 'Tidak Layak'],
        'ownership': ['Milik RS', 'Sewa', 'Pinjam Pakai', 'Hibah', 'Lainnya'],
    }
    for option_type, names in defaults.items():
        for index, name in enumerate(names, start=1):
            InventoryOption.objects.get_or_create(
                option_type=option_type,
                name=name,
                defaults={'sort_order': index, 'is_active': True},
            )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keuangan', '0026_announcement_audience'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Deskripsi Aset')),
                ('brand', models.CharField(blank=True, max_length=140, verbose_name='Merek')),
                ('location', models.CharField(blank=True, max_length=180, verbose_name='Lokasi')),
                ('foto', models.ImageField(blank=True, null=True, upload_to=keuangan.models.foto_inventory_asset_path)),
                ('manufacture_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tahun Pembuatan')),
                ('purchase_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tahun Beli')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Harga Beli')),
                ('recommended_action', models.TextField(blank=True, verbose_name='Rekomendasi Tindakan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_type', models.CharField(choices=[('unit', 'Unit'), ('category', 'Kategori Aset'), ('condition', 'Status Kelayakan'), ('ownership', 'Status Kepemilikan')], max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['option_type', 'sort_order', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryoption',
            index=models.Index(fields=['option_type', 'is_active'], name='inv_option_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryoption',
            index=models.Index(fields=['name'], name='inv_option_name_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryoption',
            unique_together={('option_type', 'name')},
        ),
        migrations.RunPython(seed_inventory_options, migrations.RunPython.noop),
        migrations.AddField(
            model_name='inventoryasset',
            name='category',
            field=models.ForeignKey(limit_choices_to={'option_type': 'category'}, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_category_assets', to='keuangan.inventoryoption'),
        ),
        migrations.AddField(
            model_name='inventoryasset',
            name='condition_status',
            field=models.ForeignKey(limit_choices_to={'option_type': 'condition'}, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_condition_assets', to='keuangan.inventoryoption'),
        ),
        migrations.AddField(
            model_name='inventoryasset',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryasset',
            name='ownership_status',
            field=models.ForeignKey(limit_choices_to={'option_type': 'ownership'}, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_ownership_assets', to='keuangan.inventoryoption'),
        ),
        migrations.AddField(
            model_name='inventoryasset',
            name='unit',
            field=models.ForeignKey(limit_choices_to={'option_type': 'unit'}, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_unit_assets', to='keuangan.inventoryoption'),
        ),
        migrations.AddIndex(
            model_name='inventoryasset',
            index=models.Index(fields=['unit', 'category'], name='inv_asset_unit_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryasset',
            index=models.Index(fields=['condition_status'], name='inv_asset_condition_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryasset',
            index=models.Index(fields=['ownership_status'], name='inv_asset_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryasset',
            index=models.Index(fields=['purchase_year'], name='inv_asset_purchase_year_idx'),
        ),
    ]
