# Generated by Django 4.2 on 2026-06-04 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keuangan', '0027_inventoryasset_inventoryoption_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pembayaranfaktur',
            options={'ordering': ['-tanggal', '-created_at'], 'verbose_name': 'Pembayaran Faktur', 'verbose_name_plural': 'Pembayaran Faktur'},
        ),
        migrations.AddField(
            model_name='faktur',
            name='adm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='faktur',
            name='alat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='faktur',
            name='ambulan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='faktur',
            name='beban',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faktur',
            name='bhp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='faktur',
            name='farmasi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='faktur',
            name='fisio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='faktur',
            name='id_pembiayaan',
            field=models.CharField(blank=True, help_text='ID dari rssams.pbiaya', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='faktur',
            name='jasa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='faktur',
            name='jenis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faktur',
            name='kamar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='faktur',
            name='lab',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='faktur',
            name='lainnya',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='faktur',
            name='nama_pembiayaan',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='faktur',
            name='periode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faktur',
            name='ppn_farmasi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='faktur',
            name='rad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='faktur',
            name='tgl_kirim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faktur',
            name='tindakan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='faktur',
            name='xround',
            field=models.CharField(default='N', help_text='Pembulatan Y/N', max_length=1),
        ),
        migrations.AlterField(
            model_name='faktur',
            name='pelanggan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faktur', to='keuangan.pelanggan'),
        ),
        migrations.AlterField(
            model_name='faktur',
            name='status',
            field=models.CharField(choices=[('belum_bayar', 'Belum Bayar'), ('bayar_sebagian', 'Bayar Sebagian'), ('lunas', 'Lunas'), ('batal', 'Dibatalkan')], default='belum_bayar', max_length=20),
        ),
        migrations.AlterField(
            model_name='pembayaranfaktur',
            name='akun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pembayaran_faktur', to='keuangan.akun'),
        ),
        migrations.CreateModel(
            name='AlokasiDana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pembiayaan', models.CharField(help_text='ID dari rssams.pbiaya', max_length=20)),
                ('nama_pembiayaan', models.CharField(help_text='Nama pembiayaan/asuransi', max_length=150)),
                ('tanggal_penerimaan', models.DateField()),
                ('jumlah_penerimaan', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bank', models.CharField(choices=[('bsi', 'BSI'), ('bri', 'BRI'), ('mandiri', 'Mandiri'), ('bca', 'BCA')], max_length=20)),
                ('total_alokasi', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sisa_alokasi', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alokasi_dana', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alokasi Dana',
                'verbose_name_plural': 'Alokasi Dana',
                'ordering': ['-tanggal_penerimaan', '-created_at'],
                'unique_together': {('id_pembiayaan', 'tanggal_penerimaan', 'bank')},
            },
        ),
        migrations.AddField(
            model_name='pembayaranfaktur',
            name='alokasi_dana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pembayaran', to='keuangan.alokasidana'),
        ),
    ]
