# Generated by Django 4.2 on 2026-06-13 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keuangan', '0032_pembayaranfaktur_status_dibatalkan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycash',
            name='laporan_disetujui_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pettycash',
            name='laporan_disetujui_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_laporan_disetujui', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pettycash',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak'), ('dicairkan', 'Dicairkan'), ('menunggu_approval_laporan', 'Menunggu Approval Laporan'), ('dilaporkan', 'Dilaporkan'), ('menunggu_pengembalian', 'Menunggu Pengembalian'), ('selesai', 'Selesai')], default='pending', max_length=30),
        ),
    ]
