# Generated by Django 4.2 on 2026-06-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0033_pettycash_laporan_disetujui_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faktur',
            name='jenis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
