# Generated by Django 4.2 on 2026-07-01 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keuangan', '0034_alter_faktur_jenis_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtangSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_siaga_faktur_id', models.CharField(help_text='ID rssams.tran_beli_brg_farmasi', max_length=32, unique=True)),
                ('nomor_spb', models.CharField(blank=True, max_length=50)),
                ('tanggal_spb', models.DateField(blank=True, null=True)),
                ('nomor_faktur', models.CharField(max_length=100)),
                ('vendor_id', models.IntegerField(help_text='ID rssams.rekanan.id_rekanan')),
                ('vendor_nama', models.CharField(blank=True, max_length=150)),
                ('tanggal_faktur', models.DateField(blank=True, null=True)),
                ('tanggal_jatuh_tempo', models.DateField(blank=True, null=True)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=25)),
                ('tanggal_titip', models.DateField(blank=True, null=True)),
                ('keterangan_titip', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('belum_dibayar', 'Belum Dibayar'), ('sebagian', 'Sebagian'), ('lunas', 'Lunas')], default='belum_dibayar', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utang_supplier_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Utang Supplier',
                'verbose_name_plural': 'Utang Supplier',
                'db_table': 'utang_supplier',
                'ordering': ['-tanggal_faktur', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PembayaranUtang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_rencana_bayar', models.DateField(blank=True, null=True)),
                ('tanggal_proses', models.DateField()),
                ('tanggal_app', models.DateField(blank=True, null=True)),
                ('jumlah_bayar', models.DecimalField(decimal_places=2, max_digits=25)),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pembayaran_utang', to=settings.AUTH_USER_MODEL)),
                ('utang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pembayaran', to='keuangan.utangsupplier')),
            ],
            options={
                'verbose_name': 'Pembayaran Utang',
                'verbose_name_plural': 'Pembayaran Utang',
                'db_table': 'pembayaran_utang',
                'ordering': ['-tanggal_proses', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='utangsupplier',
            index=models.Index(fields=['app_siaga_faktur_id'], name='utang_app_siaga_idx'),
        ),
        migrations.AddIndex(
            model_name='utangsupplier',
            index=models.Index(fields=['vendor_id'], name='utang_vendor_idx'),
        ),
        migrations.AddIndex(
            model_name='utangsupplier',
            index=models.Index(fields=['status'], name='utang_status_idx'),
        ),
        migrations.AddIndex(
            model_name='utangsupplier',
            index=models.Index(fields=['tanggal_jatuh_tempo'], name='utang_jtempo_idx'),
        ),
        migrations.AddIndex(
            model_name='pembayaranutang',
            index=models.Index(fields=['utang', 'tanggal_proses'], name='payutang_utang_tgl_idx'),
        ),
        migrations.AddIndex(
            model_name='pembayaranutang',
            index=models.Index(fields=['created_at'], name='payutang_created_idx'),
        ),
    ]
