# Generated by Django 4.2 on 2026-07-14 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keuangan', '0035_utangsupplier_pembayaranutang_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogistikBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=160)),
                ('kemasan', models.CharField(blank=True, max_length=80)),
                ('satuan', models.CharField(max_length=40)),
                ('isi', models.PositiveIntegerField(default=1)),
                ('merk', models.CharField(blank=True, max_length=100)),
                ('golongan', models.CharField(blank=True, max_length=100)),
                ('stok', models.IntegerField(default=0)),
                ('stok_minimum', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistik_barang_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nama_barang'],
            },
        ),
        migrations.CreateModel(
            name='LogistikBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('isi', models.PositiveIntegerField(default=1)),
                ('harga', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('jml_mutasi', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_logistik', to='keuangan.logistikbarang')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LogistikPermintaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.localdate)),
                ('ruang', models.CharField(max_length=120)),
                ('qty_minta', models.PositiveIntegerField()),
                ('qty_setuju', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='menunggu', max_length=20)),
                ('catatan', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permintaan_logistik', to='keuangan.logistikbarang')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistik_permintaan_created', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistik_permintaan_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogistikPembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(blank=True, max_length=30, unique=True)),
                ('tanggal', models.DateField(default=django.utils.timezone.localdate)),
                ('pemasok', models.CharField(blank=True, max_length=150)),
                ('no_faktur', models.CharField(blank=True, max_length=80)),
                ('keterangan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('selesai', 'Selesai')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistik_pembelian_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogistikOpname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.localdate)),
                ('real_stock', models.IntegerField()),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opname_logistik', to='keuangan.logistikbarang')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistik_opname_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogistikMutasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(blank=True, max_length=30)),
                ('tanggal', models.DateField(default=django.utils.timezone.localdate)),
                ('ruang', models.CharField(max_length=120)),
                ('qty', models.PositiveIntegerField()),
                ('harga', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mutasi_logistik', to='keuangan.logistikbarang')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mutasi_items', to='keuangan.logistikbatch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistik_mutasi_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='logistikbatch',
            name='pembelian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='keuangan.logistikpembelian'),
        ),
        migrations.AddIndex(
            model_name='logistikmutasi',
            index=models.Index(fields=['barang', 'tanggal'], name='log_mutasi_barang_tgl_idx'),
        ),
        migrations.AddIndex(
            model_name='logistikbarang',
            index=models.Index(fields=['nama_barang'], name='log_barang_nama_idx'),
        ),
        migrations.AddIndex(
            model_name='logistikbarang',
            index=models.Index(fields=['is_active', 'stok'], name='log_barang_active_stok_idx'),
        ),
    ]
