# Generated by Django 4.2 on 2026-07-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0036_logistikbarang_logistikbatch_logistikpermintaan_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='utangsupplier',
            name='utang_app_siaga_idx',
        ),
        migrations.AddField(
            model_name='utangsupplier',
            name='sumber',
            field=models.CharField(choices=[('farmasi', 'Farmasi'), ('logistik', 'Logistik')], default='farmasi', help_text='Asal transaksi: farmasi atau logistik', max_length=10),
        ),
        migrations.AlterField(
            model_name='utangsupplier',
            name='app_siaga_faktur_id',
            field=models.CharField(help_text='ID dari tabel sumber (tran_beli_brg_farmasi atau tran_beli_brg_log)', max_length=32),
        ),
        migrations.AddIndex(
            model_name='utangsupplier',
            index=models.Index(fields=['sumber'], name='utang_sumber_idx'),
        ),
        migrations.AddConstraint(
            model_name='utangsupplier',
            constraint=models.UniqueConstraint(fields=('app_siaga_faktur_id', 'sumber'), name='utang_faktur_sumber_uniq'),
        ),
    ]
