# Generated by Django 4.2 on 2026-07-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0037_utangsupplier_sumber_composite_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utangsupplier',
            name='sumber',
            field=models.CharField(choices=[('farmasi', 'Farmasi'), ('logistik', 'Logistik'), ('manual', 'Manual')], default='farmasi', help_text='Asal transaksi: farmasi atau logistik', max_length=10),
        ),
    ]
