# Generated by Django 4.2 on 2026-07-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0039_add_sumber_to_rekanan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembayaranutang',
            name='status',
            field=models.CharField(choices=[('pending', 'Dalam Pengajuan'), ('realisasi', 'Realisasi'), ('ditolak', 'Ditolak')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='utangsupplier',
            name='status',
            field=models.CharField(choices=[('belum_dibayar', 'Belum Dibayar'), ('diajukan', 'Diajukan'), ('sebagian', 'Sebagian'), ('sebagian_diajukan', 'Sebagian Diajukan'), ('lunas', 'Lunas')], default='belum_dibayar', max_length=20),
        ),
        migrations.AddIndex(
            model_name='pembayaranutang',
            index=models.Index(fields=['status'], name='payutang_status_idx'),
        ),
    ]
