# Generated by Django 4.2 on 2026-07-25 02:09

from django.db import migrations, models
from django.db.models import Sum


def migrate_pembayaran_status(apps, schema_editor):
    PembayaranUtang = apps.get_model('keuangan', 'PembayaranUtang')
    qs = PembayaranUtang.objects.filter(status='realisasi')
    for p in qs:
        p.status = 'realisasi_lunas'
        p.save()
        
        utang = p.utang
        total_realisasi = utang.pembayaran.filter(status__in=['realisasi_sebagian', 'realisasi_lunas']).aggregate(total=Sum('jumlah_bayar'))['total'] or 0
        total_pending = utang.pembayaran.filter(status='pending').aggregate(total=Sum('jumlah_bayar'))['total'] or 0
        
        if total_realisasi >= utang.nominal:
            utang.status = 'lunas'
        elif total_realisasi > 0:
            if total_pending > 0:
                utang.status = 'sebagian_diajukan'
            else:
                utang.status = 'sebagian'
        else:
            if total_pending > 0:
                utang.status = 'diajukan'
            else:
                utang.status = 'belum_dibayar'
        utang.save(update_fields=['status'])


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0040_pembayaranutang_status_alter_utangsupplier_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaranutang',
            name='status',
            field=models.CharField(choices=[('pending', 'Dalam Pengajuan'), ('realisasi_sebagian', 'Realisasi Sebagian'), ('realisasi_lunas', 'Realisasi Pelunasan'), ('ditolak', 'Ditolak')], default='pending', max_length=20),
        ),
        migrations.RunPython(migrate_pembayaran_status, reverse_code=migrations.RunPython.noop),
    ]
