# Generated by Django 4.2 on 2026-07-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0041_alter_pembayaranutang_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistikbatch',
            name='qty_pesan',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='logistikbatch',
            name='qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
