# Generated by Django 4.2 on 2026-07-31 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0043_faktur_kembalikan_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='faktur',
            name='is_cob',
            field=models.BooleanField(default=False, help_text='Penjaminan ganda COB (BPJS + Asuransi)'),
        ),
        migrations.AddField(
            model_name='faktur',
            name='tanggungan_bpjs',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Nominal INA-CBGs / Tanggungan BPJS', max_digits=15),
        ),
        migrations.AddField(
            model_name='faktur',
            name='total_real_rs',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total biaya riil RS sebelum dipotong BPJS', max_digits=15),
        ),
    ]
