# Generated by Django 4.2 on 2026-08-04 03:35

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keuangan', '0044_faktur_is_cob_faktur_tanggungan_bpjs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembayaranutang',
            name='jumlah_kas_keluar',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Nominal aktual kas/bank yang dikeluarkan', max_digits=25),
        ),
        migrations.AddField(
            model_name='pembayaranutang',
            name='potongan_deposit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Nominal potongan dari deposit retur vendor', max_digits=25),
        ),
        migrations.CreateModel(
            name='DepositVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.IntegerField(db_index=True, help_text='ID rssams.rekanan.id_rekanan')),
                ('vendor_nama', models.CharField(blank=True, max_length=150)),
                ('nominal_retur', models.DecimalField(decimal_places=2, max_digits=25)),
                ('terpakai', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=25)),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_vendor_created', to=settings.AUTH_USER_MODEL)),
                ('utang_asal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_terbuat', to='keuangan.utangsupplier')),
            ],
            options={
                'verbose_name': 'Deposit Vendor (Retur)',
                'verbose_name_plural': 'Deposit Vendor (Retur)',
                'db_table': 'deposit_vendor',
                'ordering': ['-created_at'],
            },
        ),
    ]
