# Generated by Django 4.2 on 2026-08-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0045_pembayaranutang_jumlah_kas_keluar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utangsupplier',
            name='kategori',
            field=models.CharField(blank=True, help_text='Kategori barang/faktur (e.g. ALAT KESEHATAN, OBAT DAN BHP, ATK)', max_length=100),
        ),
        migrations.AlterField(
            model_name='pembayaranutang',
            name='status',
            field=models.CharField(choices=[('pending', 'Dalam Pengajuan'), ('realisasi_sebagian', 'Realisasi Sebagian'), ('realisasi_lunas', 'Realisasi Pelunasan'), ('ditolak', 'Ditolak'), ('retur', 'Retur Barang')], default='pending', max_length=20),
        ),
    ]
