# Generated by Django 4.2 on 2026-08-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0046_utangsupplier_kategori_alter_pembayaranutang_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='utangsupplier',
            index=models.Index(fields=['nomor_spb'], name='utang_nspb_idx'),
        ),
        migrations.AddIndex(
            model_name='utangsupplier',
            index=models.Index(fields=['nomor_faktur'], name='utang_nfaktur_idx'),
        ),
        migrations.AddIndex(
            model_name='utangsupplier',
            index=models.Index(fields=['app_siaga_faktur_id'], name='utang_siagafak_idx'),
        ),
        migrations.AddIndex(
            model_name='utangsupplier',
            index=models.Index(fields=['kategori'], name='utang_kategori_idx'),
        ),
    ]
