# Generated by Django 4.2 on 2026-08-18 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0049_alter_akun_table_alter_alokasidana_table_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventoryoption',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='itbackuprecord',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='itcredentialnote',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='itremoteaccess',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='itrepairrequest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='itrepairrequest',
            name='requester_user',
        ),
        migrations.RemoveField(
            model_name='itsubscription',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='InventoryAsset',
        ),
        migrations.DeleteModel(
            name='InventoryOption',
        ),
        migrations.DeleteModel(
            name='ITBackupRecord',
        ),
        migrations.DeleteModel(
            name='ITCredentialNote',
        ),
        migrations.DeleteModel(
            name='ITRemoteAccess',
        ),
        migrations.DeleteModel(
            name='ITRepairRequest',
        ),
        migrations.DeleteModel(
            name='ITSubscription',
        ),
    ]
