# Generated by Django 4.2 on 2026-08-18 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0050_alter_inventoryoption_unique_together_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='logistikbatch',
                    name='barang',
                ),
                migrations.RemoveField(
                    model_name='logistikbatch',
                    name='pembelian',
                ),
                migrations.RemoveField(
                    model_name='logistikmutasi',
                    name='barang',
                ),
                migrations.RemoveField(
                    model_name='logistikmutasi',
                    name='batch',
                ),
                migrations.RemoveField(
                    model_name='logistikmutasi',
                    name='created_by',
                ),
                migrations.RemoveField(
                    model_name='logistikopname',
                    name='barang',
                ),
                migrations.RemoveField(
                    model_name='logistikopname',
                    name='created_by',
                ),
                migrations.RemoveField(
                    model_name='logistikpembelian',
                    name='created_by',
                ),
                migrations.RemoveField(
                    model_name='logistikpermintaan',
                    name='barang',
                ),
                migrations.RemoveField(
                    model_name='logistikpermintaan',
                    name='created_by',
                ),
                migrations.RemoveField(
                    model_name='logistikpermintaan',
                    name='verified_by',
                ),
                migrations.DeleteModel(
                    name='LogistikBarang',
                ),
                migrations.DeleteModel(
                    name='LogistikBatch',
                ),
                migrations.DeleteModel(
                    name='LogistikMutasi',
                ),
                migrations.DeleteModel(
                    name='LogistikOpname',
                ),
                migrations.DeleteModel(
                    name='LogistikPembelian',
                ),
                migrations.DeleteModel(
                    name='LogistikPermintaan',
                ),
            ],
            database_operations=[],
        ),
    ]
