# Generated by Django 4.2 on 2026-08-19 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0051_remove_logistikbatch_barang_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='announcementread',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='announcementread',
            name='announcement',
        ),
        migrations.RemoveField(
            model_name='announcementread',
            name='user',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='fotolaporanperjalanan',
            name='laporan',
        ),
        migrations.RemoveField(
            model_name='idempotencylog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='laporanperjalanan',
            name='log_perjalanan',
        ),
        migrations.RemoveField(
            model_name='logbbm',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='logbbm',
            name='kendaraan',
        ),
        migrations.RemoveField(
            model_name='logmaintenance',
            name='dilaporkan_oleh',
        ),
        migrations.RemoveField(
            model_name='logmaintenance',
            name='kendaraan',
        ),
        migrations.RemoveField(
            model_name='logperjalanan',
            name='disetujui_oleh',
        ),
        migrations.RemoveField(
            model_name='logperjalanan',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='logperjalanan',
            name='kendaraan',
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='AnnouncementRead',
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='FotoLaporanPerjalanan',
        ),
        migrations.DeleteModel(
            name='IdempotencyLog',
        ),
        migrations.DeleteModel(
            name='Kendaraan',
        ),
        migrations.DeleteModel(
            name='LaporanPerjalanan',
        ),
        migrations.DeleteModel(
            name='LogBBM',
        ),
        migrations.DeleteModel(
            name='LogMaintenance',
        ),
        migrations.DeleteModel(
            name='LogPerjalanan',
        ),
    ]
