# Generated by Django 4.2 on 2026-08-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0052_alter_announcementread_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pettycash',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak'), ('dicairkan', 'Dicairkan'), ('menunggu_approval_laporan', 'Menunggu Approval Laporan'), ('dilaporkan', 'Dilaporkan'), ('menunggu_pengembalian', 'Menunggu Pengembalian'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak'), ('dicairkan', 'Dicairkan'), ('dibatalkan', 'Dibatalkan')], default='pending', max_length=20),
        ),
    ]
