# Generated by Django 4.2 on 2026-08-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0053_alter_pettycash_status_alter_reimbursement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utangsupplier',
            name='sumber',
            field=models.CharField(choices=[('farmasi', 'Farmasi'), ('logistik', 'Logistik'), ('manual', 'Manual'), ('keuangan', 'Keuangan')], default='farmasi', help_text='Asal transaksi: farmasi atau logistik', max_length=10),
        ),
    ]
