# Generated by Django 4.2 on 2026-08-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0054_alter_utangsupplier_sumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengajuanpenambahansaldo',
            name='keterangan',
            field=models.TextField(blank=True, default=''),
        ),
    ]
