# Generated by Django 4.2 on 2026-08-31 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keuangan', '0055_pengajuanpenambahansaldo_keterangan'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndukPembiayaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Nama Induk Pembiayaan / Payor Group', max_length=150, unique=True)),
                ('kode', models.CharField(blank=True, help_text='Kode singkatan / identitas', max_length=50)),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='induk_pembiayaan_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Induk Pembiayaan',
                'verbose_name_plural': 'Daftar Induk Pembiayaan',
                'db_table': 'keuangan_induk_pembiayaan',
                'ordering': ['nama'],
            },
        ),
        migrations.AddField(
            model_name='alokasidana',
            name='is_induk',
            field=models.BooleanField(default=False, help_text='True jika alokasi dana untuk seluruh anak di bawah induk'),
        ),
        migrations.AlterField(
            model_name='alokasidana',
            name='id_pembiayaan',
            field=models.CharField(blank=True, default='', help_text='ID dari rssams.pbiaya atau kosong jika induk pool', max_length=20),
        ),
        migrations.AlterField(
            model_name='alokasidana',
            name='nama_pembiayaan',
            field=models.CharField(help_text='Nama pembiayaan/asuransi atau nama induk', max_length=150),
        ),
        migrations.CreateModel(
            name='PembiayaanIndukMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pembiayaan', models.CharField(db_index=True, help_text='ID dari rssams.pbiaya', max_length=20, unique=True)),
                ('nama_pembiayaan', models.CharField(blank=True, help_text='Nama pembiayaan/asuransi anak', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pembiayaan_mapping_created', to=settings.AUTH_USER_MODEL)),
                ('induk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anggota', to='keuangan.indukpembiayaan')),
            ],
            options={
                'verbose_name': 'Pemetaan Induk Pembiayaan',
                'verbose_name_plural': 'Pemetaan Induk Pembiayaan',
                'db_table': 'keuangan_pembiayaan_induk_mapping',
                'ordering': ['nama_pembiayaan'],
            },
        ),
        migrations.AddField(
            model_name='alokasidana',
            name='induk_pembiayaan',
            field=models.ForeignKey(blank=True, help_text='Jika alokasi ini adalah pool induk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alokasi_dana', to='keuangan.indukpembiayaan'),
        ),
    ]
