# Generated by Django 4.2 on 2026-09-01 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keuangan', '0056_indukpembiayaan_alokasidana_is_induk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utangsupplier',
            name='alasan_batal',
            field=models.TextField(blank=True, help_text='Alasan pembatalan catatan utang/faktur'),
        ),
        migrations.AddField(
            model_name='utangsupplier',
            name='dibatalkan_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utangsupplier',
            name='dibatalkan_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utang_supplier_dibatalkan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='utangsupplier',
            name='status',
            field=models.CharField(choices=[('belum_dibayar', 'Belum Dibayar'), ('diajukan', 'Diajukan'), ('sebagian', 'Sebagian'), ('sebagian_diajukan', 'Sebagian Diajukan'), ('lunas', 'Lunas'), ('dibatalkan', 'Dibatalkan')], default='belum_dibayar', max_length=20),
        ),
    ]
