# Generated by Django 4.2 on 2026-09-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0057_utangsupplier_alasan_batal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporanpenggunaan',
            name='tanggal_nota',
            field=models.DateField(blank=True, help_text='Tanggal nota / kuitansi riil belanja', null=True),
        ),
    ]
