# Generated by Django 4.2 on 2026-09-01 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0058_laporanpenggunaan_tanggal_nota'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLaporanPenggunaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_akun', models.CharField(max_length=30)),
                ('nama_akun', models.CharField(max_length=150)),
                ('pos_biaya', models.CharField(blank=True, max_length=100)),
                ('deskripsi', models.TextField()),
                ('nilai', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='keuangan.laporanpenggunaan')),
            ],
            options={
                'verbose_name': 'Item Laporan Penggunaan',
                'verbose_name_plural': 'Item Laporan Penggunaan',
                'db_table': 'petty_cash_laporan_item',
                'ordering': ['id'],
            },
        ),
    ]
