# Generated by Django 4.2 on 2026-09-01 07:01

from django.db import migrations, models
import keuangan.models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0059_itemlaporanpenggunaan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotolaporanpenggunaan',
            name='foto',
            field=models.FileField(upload_to=keuangan.models.foto_laporan_penggunaan_path),
        ),
    ]
