# Generated by Django 4.2 on 2026-09-02 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import keuangan.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keuangan', '0060_alter_fotolaporanpenggunaan_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='KasBesar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_pengajuan', models.CharField(editable=False, max_length=20, unique=True)),
                ('tanggal', models.DateField()),
                ('keperluan', models.TextField()),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('keterangan', models.TextField(blank=True)),
                ('berkas', models.FileField(blank=True, null=True, upload_to=keuangan.models.berkas_kb_path)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak'), ('dicairkan', 'Dicairkan'), ('menunggu_approval_laporan', 'Menunggu Approval Laporan'), ('dilaporkan', 'Dilaporkan'), ('menunggu_pengembalian', 'Menunggu Pengembalian'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='pending', max_length=30)),
                ('catatan_tolak', models.TextField(blank=True)),
                ('alasan_batal', models.TextField(blank=True)),
                ('laporan_disetujui_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kas_besar_pengajuan', to=settings.AUTH_USER_MODEL)),
                ('dicairkan_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kas_besar_dicairkan', to=settings.AUTH_USER_MODEL)),
                ('disetujui_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kas_besar_disetujui', to=settings.AUTH_USER_MODEL)),
                ('laporan_disetujui_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kas_besar_laporan_disetujui', to=settings.AUTH_USER_MODEL)),
                ('sumber_petty_cash', models.ForeignKey(blank=True, help_text='Referensi Petty Cash jika ini adalah hasil pengalihan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kas_besar_pengalihan', to='keuangan.pettycash')),
            ],
            options={
                'verbose_name': 'Kas Besar',
                'verbose_name_plural': 'Kas Besar',
                'db_table': 'keuangan_kas_besar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LaporanPenggunaanKasBesar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_laporan', models.DateField()),
                ('tanggal_nota', models.DateField(blank=True, help_text='Tanggal nota / kuitansi riil belanja', null=True)),
                ('nominal_digunakan', models.DecimalField(decimal_places=2, max_digits=15)),
                ('selisih', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('rincian', models.TextField()),
                ('nota', models.FileField(blank=True, null=True, upload_to=keuangan.models.nota_kb_path)),
                ('pengembalian_selesai', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dikonfirmasi_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='konfirmasi_laporan_kb', to=settings.AUTH_USER_MODEL)),
                ('kas_besar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laporan', to='keuangan.kasbesar')),
            ],
            options={
                'verbose_name': 'Laporan Penggunaan Kas Besar',
                'verbose_name_plural': 'Laporan Penggunaan Kas Besar',
                'db_table': 'keuangan_kas_besar_laporan',
            },
        ),
        migrations.CreateModel(
            name='ItemLaporanKasBesar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_akun', models.CharField(max_length=30)),
                ('nama_akun', models.CharField(max_length=150)),
                ('pos_biaya', models.CharField(blank=True, max_length=100)),
                ('deskripsi', models.TextField()),
                ('nilai', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='keuangan.laporanpenggunaankasbesar')),
            ],
            options={
                'verbose_name': 'Item Laporan Kas Besar',
                'verbose_name_plural': 'Item Laporan Kas Besar',
                'db_table': 'keuangan_kas_besar_laporan_item',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FotoLaporanKasBesar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(upload_to=keuangan.models.foto_laporan_kb_path)),
                ('urutan', models.PositiveIntegerField(default=1, help_text='Urutan foto')),
                ('keterangan', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_list', to='keuangan.laporanpenggunaankasbesar')),
            ],
            options={
                'verbose_name': 'Foto Laporan Kas Besar',
                'verbose_name_plural': 'Foto Laporan Kas Besar',
                'db_table': 'keuangan_kas_besar_foto_laporan',
                'ordering': ['urutan', 'created_at'],
            },
        ),
    ]
