# Generated by Django 4.2 on 2026-09-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0061_kasbesar_laporanpenggunaankasbesar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kasbesar',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('menunggu_realisasi', 'Menunggu Realisasi'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak'), ('dicairkan', 'Dicairkan'), ('menunggu_approval_laporan', 'Menunggu Approval Laporan'), ('dilaporkan', 'Dilaporkan'), ('menunggu_pengembalian', 'Menunggu Pengembalian'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='pending', max_length=30),
        ),
    ]
