# Generated by Django 4.2 on 2026-09-03 00:18

from django.db import migrations, models
import keuangan.models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0062_alter_kasbesar_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengajuanpenambahansaldo',
            name='berkas',
            field=models.FileField(blank=True, help_text='Lampiran print out / rekap Laporan PC', null=True, upload_to=keuangan.models.berkas_saldo_path),
        ),
    ]
