# Generated by Django 4.2 on 2026-09-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0063_pengajuanpenambahansaldo_berkas'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='tanggal_nota',
            field=models.DateField(blank=True, help_text='Tanggal bukti transaksi nota/kuitansi fisik', null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='tanggal',
            field=models.DateField(help_text='Tanggal pengajuan (hari ini)'),
        ),
    ]
