# Generated by Django 4.2 on 2026-09-03 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0064_reimbursement_tanggal_nota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='kas_besar',
            field=models.ForeignKey(blank=True, help_text='Referensi Kas Besar jika reimbursement berasal dari kekurangan belanja', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursements', to='keuangan.kasbesar'),
        ),
        migrations.AlterField(
            model_name='kasbesar',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('menunggu_realisasi', 'Menunggu Realisasi'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak'), ('dicairkan', 'Dicairkan'), ('menunggu_approval_laporan', 'Menunggu Approval Laporan'), ('dilaporkan', 'Dilaporkan'), ('menunggu_pengembalian', 'Menunggu Pengembalian'), ('menunggu_reimburse', 'Menunggu Reimbursement'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='pending', max_length=30),
        ),
    ]
