# Generated by Django 4.2 on 2026-09-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0065_reimbursement_kas_besar_alter_kasbesar_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlaporankasbesar',
            name='harga_satuan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='itemlaporankasbesar',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='itemlaporanpenggunaan',
            name='harga_satuan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='itemlaporanpenggunaan',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='laporanpenggunaan',
            name='diskon',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='laporanpenggunaan',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='laporanpenggunaankasbesar',
            name='diskon',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='laporanpenggunaankasbesar',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak'), ('dicairkan', 'Dicairkan'), ('lunas', 'Lunas'), ('dibatalkan', 'Dibatalkan')], default='pending', max_length=20),
        ),
    ]
