# Generated by Django 4.2 on 2026-10-05 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0066_itemlaporankasbesar_harga_satuan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='petty_cash',
            field=models.ForeignKey(blank=True, help_text='Referensi Petty Cash jika reimbursement berasal dari kekurangan belanja', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursements', to='keuangan.pettycash'),
        ),
        migrations.AlterField(
            model_name='pettycash',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak'), ('dicairkan', 'Dicairkan'), ('menunggu_approval_laporan', 'Menunggu Approval Laporan'), ('dilaporkan', 'Dilaporkan'), ('menunggu_pengembalian', 'Menunggu Pengembalian'), ('menunggu_reimburse', 'Menunggu Reimbursement'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='pending', max_length=30),
        ),
    ]
