# Generated by Django 4.2 on 2026-08-18 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import it.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ITSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('service_type', models.CharField(choices=[('domain', 'Domain'), ('hosting', 'Hosting'), ('ssl', 'SSL'), ('internet', 'Internet'), ('software', 'Software / Lisensi'), ('vendor', 'Vendor / Support'), ('other', 'Lainnya')], default='software', max_length=30)),
                ('vendor', models.CharField(blank=True, max_length=160)),
                ('account_ref', models.CharField(blank=True, max_length=180)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('pic', models.CharField(blank=True, max_length=120)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Bulanan'), ('quarterly', 'Triwulan'), ('semester', 'Semester'), ('yearly', 'Tahunan'), ('one_time', 'Sekali Bayar')], default='yearly', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('expiring', 'Hampir Habis'), ('expired', 'Expired'), ('cancelled', 'Dibatalkan')], default='active', max_length=20)),
                ('reminder_days', models.PositiveIntegerField(default=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'it_subscription',
                'ordering': ['end_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ITRepairRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('requester_name', models.CharField(blank=True, max_length=120)),
                ('unit', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software'), ('network', 'Jaringan'), ('printer', 'Printer'), ('account', 'Akun / Akses'), ('simak', 'SIMAK'), ('other', 'Lainnya')], default='other', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Rendah'), ('normal', 'Normal'), ('high', 'Tinggi'), ('urgent', 'Darurat')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Baru'), ('in_progress', 'Diproses'), ('waiting', 'Menunggu'), ('done', 'Selesai'), ('cancelled', 'Dibatalkan')], default='open', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('resolution', models.TextField(blank=True)),
                ('sparepart', models.CharField(blank=True, max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=it.models.foto_it_repair_path)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_repair_requests', to=settings.AUTH_USER_MODEL)),
                ('requester_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_reported_repairs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'it_repair_request',
                'ordering': ['-requested_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ITRemoteAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=160)),
                ('user_owner', models.CharField(blank=True, max_length=120)),
                ('unit', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('anydesk_id', models.CharField(blank=True, max_length=80)),
                ('rustdesk_id', models.CharField(blank=True, max_length=80)),
                ('access_password', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('inactive', 'Nonaktif'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_remote_access_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'it_remote_access',
                'ordering': ['device_name'],
            },
        ),
        migrations.CreateModel(
            name='ITCredentialNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('website', 'Website'), ('server', 'Server'), ('database', 'Database'), ('email', 'Email'), ('device', 'Perangkat'), ('vendor', 'Vendor'), ('other', 'Lainnya')], default='website', max_length=30)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('username', models.CharField(blank=True, max_length=180)),
                ('password', models.TextField(blank=True)),
                ('owner', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_credential_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'it_credential_note',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ITBackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('full', 'Full Backup'), ('incremental', 'Incremental Backup'), ('differential', 'Differential Backup'), ('database', 'Database Only'), ('files', 'Files Only')], default='database', max_length=30)),
                ('status', models.CharField(choices=[('success', 'Sukses'), ('failed', 'Gagal'), ('in_progress', 'Sedang Berjalan'), ('warning', 'Selesai (dengan Peringatan)')], default='success', max_length=20)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('storage_path', models.CharField(blank=True, max_length=500)),
                ('file_size_mb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_backup_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'it_backup_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='itsubscription',
            index=models.Index(fields=['status', 'end_date'], name='it_sub_status_end_idx'),
        ),
        migrations.AddIndex(
            model_name='itsubscription',
            index=models.Index(fields=['service_type', 'end_date'], name='it_sub_type_end_idx'),
        ),
        migrations.AddIndex(
            model_name='itrepairrequest',
            index=models.Index(fields=['status', 'priority'], name='it_ticket_status_idx'),
        ),
        migrations.AddIndex(
            model_name='itrepairrequest',
            index=models.Index(fields=['requested_at'], name='it_ticket_requested_idx'),
        ),
        migrations.AddIndex(
            model_name='itremoteaccess',
            index=models.Index(fields=['status', 'device_name'], name='it_remote_status_idx'),
        ),
        migrations.AddIndex(
            model_name='itremoteaccess',
            index=models.Index(fields=['unit'], name='it_remote_unit_idx'),
        ),
        migrations.AddIndex(
            model_name='itcredentialnote',
            index=models.Index(fields=['category', 'is_active'], name='it_credential_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='itcredentialnote',
            index=models.Index(fields=['name'], name='it_credential_name_idx'),
        ),
        migrations.AddIndex(
            model_name='itbackuprecord',
            index=models.Index(fields=['status', '-created_at'], name='it_backup_status_idx'),
        ),
        migrations.AddIndex(
            model_name='itbackuprecord',
            index=models.Index(fields=['backup_type', '-created_at'], name='it_backup_type_idx'),
        ),
    ]
