# Generated by Django 4.2 on 2026-03-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('karyawan', 'Karyawan'), ('kasir', 'Kasir'), ('manajer_keuangan', 'Manajer Keuangan'), ('direktur', 'Direktur')], default='karyawan', max_length=20),
        ),
    ]
