# Generated by Django 4.2 on 2026-03-30 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_active_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Daftar Unit',
                'ordering': ['nama'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('direktur', 'Direktur'), ('wadir_keuangan', 'Wadir Keuangan & Umum'), ('wadir_pelayanan', 'Wadir Pelayanan & Penunjang'), ('manajer_keuangan', 'Manajer Keuangan'), ('kasir', 'Kasir'), ('karyawan', 'Karyawan')], default='karyawan', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.unit'),
        ),
    ]
