# Generated by Django 4.2 on 2026-04-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_unit_alter_user_role_user_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('direktur', 'Direktur'), ('wadir_keuangan', 'Wadir Keuangan & Umum'), ('wadir_pelayanan', 'Wadir Pelayanan & Penunjang'), ('manajer_keuangan', 'Manajer Keuangan'), ('kasir', 'Kasir'), ('karyawan', 'Karyawan'), ('driver', 'Driver')], default='karyawan', max_length=20),
        ),
    ]
