# Generated by Django 4.2 on 2026-05-15 12:30

from django.db import migrations, models


def migrate_role_levels(apps, schema_editor):
    User = apps.get_model('users', 'User')
    mapping = {
        'direktur': ('direktur', False, False),
        'wadir_keuangan': ('wakil_direktur', False, False),
        'wadir_pelayanan': ('wakil_direktur', False, False),
        'manajer_keuangan': ('manajer', False, False),
        'it': ('karyawan', False, True),
        'driver': ('karyawan', True, False),
        'kasir': ('karyawan', False, False),
        'karyawan': ('karyawan', False, False),
    }
    for user in User.objects.all():
        new_role, is_driver, is_it = mapping.get(user.role, ('karyawan', False, False))
        user.role = new_role
        user.is_driver = bool(user.is_driver or is_driver)
        user.is_it = bool(user.is_it or is_it)
        user.save(update_fields=['role', 'is_driver', 'is_it'])


def reverse_role_levels(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for user in User.objects.all():
        if user.role == 'wakil_direktur':
            user.role = 'wadir_keuangan'
        elif user.role == 'manajer':
            user.role = 'manajer_keuangan'
        elif user.is_it:
            user.role = 'it'
        elif user.is_driver:
            user.role = 'driver'
        else:
            user.role = 'karyawan'
        user.save(update_fields=['role'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_it',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(migrate_role_levels, reverse_role_levels),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('karyawan', 'Karyawan'), ('kepala_seksi', 'Kepala Seksi'), ('manajer', 'Manajer'), ('wakil_direktur', 'Wakil Direktur'), ('direktur', 'Direktur')], default='karyawan', max_length=30),
        ),
    ]
