# Generated by Django 4.2 on 2026-06-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_driver_user_is_it_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_keuangan',
            field=models.BooleanField(default=False),
        ),
    ]
