# Generated by Django 4.2 on 2026-06-15 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_is_keuangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_petty_cash_cashier',
            field=models.BooleanField(default=False),
        ),
    ]
