# Generated by Django 4.2 on 2026-07-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_is_petty_cash_cashier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='akses_catatan_utang_obat_bhp',
            field=models.BooleanField(default=False),
        ),
    ]
