# Generated by Django 4.2 on 2026-07-03 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_akses_catatan_utang_obat_bhp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='akses_catatan_utang_obat_bhp',
            new_name='akses_catatan_utang',
        ),
    ]
