# Generated by Django 4.2 on 2026-07-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_akses_catatan_utang'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_logistik',
            field=models.BooleanField(default=False),
        ),
    ]
