# Generated by Django 4.2 on 2026-08-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_is_logistik'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_akuntansi',
            field=models.BooleanField(default=False),
        ),
    ]
