# Generated by Django 4.2 on 2026-09-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_is_akuntansi'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='akses_kas_besar',
            field=models.BooleanField(default=False),
        ),
    ]
