# Generated by Django 4.2 on 2026-09-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_akses_kas_besar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='akses_reimbursement',
            field=models.BooleanField(default=False),
        ),
    ]
