# Generated by Django 4.2 on 2026-10-08 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_is_sdm'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='kategori',
            field=models.CharField(choices=[('direktorat', 'Direktorat / Wadir'), ('bidang', 'Bidang / Bagian (Manajer)'), ('seksi', 'Seksi / Sub-Bagian (Kasi)'), ('unit', 'Unit / Instalasi Pelaksana')], default='unit', max_length=30),
        ),
        migrations.AddField(
            model_name='unit',
            name='kepala_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_yang_dipimpin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='users.unit'),
        ),
        migrations.AddField(
            model_name='unit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
