# Generated by Django 4.2 on 2026-08-19 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import driver.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kendaraan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plat_nomor', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(help_text='Contoh: Avanza Putih, Ambulans 1', max_length=100)),
                ('jenis', models.CharField(choices=[('mobil', 'Mobil'), ('motor', 'Motor'), ('ambulans', 'Ambulans'), ('pickup', 'Pickup'), ('bus', 'Bus'), ('lainnya', 'Lainnya')], default='mobil', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kendaraan',
                'verbose_name_plural': 'Daftar Kendaraan',
                'db_table': 'driver_kendaraan',
                'ordering': ['jenis', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='LogPerjalanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_perjalanan', models.CharField(blank=True, editable=False, max_length=25, unique=True)),
                ('tanggal', models.DateField()),
                ('jam_berangkat', models.TimeField()),
                ('jam_kembali', models.TimeField(blank=True, null=True)),
                ('tujuan', models.CharField(max_length=255)),
                ('km_awal', models.PositiveIntegerField(help_text='KM odometer saat berangkat')),
                ('km_akhir', models.PositiveIntegerField(blank=True, help_text='KM odometer saat kembali', null=True)),
                ('jarak_km', models.PositiveIntegerField(blank=True, help_text='Otomatis dihitung', null=True)),
                ('penumpang', models.CharField(blank=True, help_text='Nama penumpang jika ada', max_length=255)),
                ('keterangan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak'), ('dilaporkan', 'Dilaporkan'), ('selesai', 'Selesai')], default='pending', max_length=20)),
                ('catatan_tolak', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disetujui_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_log_perjalanan', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_perjalanan', to=settings.AUTH_USER_MODEL)),
                ('kendaraan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log_perjalanan', to='driver.kendaraan')),
            ],
            options={
                'verbose_name': 'Log Perjalanan',
                'verbose_name_plural': 'Log Perjalanan',
                'db_table': 'driver_log_perjalanan',
                'ordering': ['-tanggal', '-jam_berangkat'],
            },
        ),
        migrations.CreateModel(
            name='LogMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('servis_rutin', 'Servis Rutin'), ('ganti_oli', 'Ganti Oli'), ('ban', 'Ganti / Tambal Ban'), ('aki', 'Ganti Aki'), ('rem', 'Perbaikan Rem'), ('ac', 'Servis AC'), ('body', 'Perbaikan Body'), ('lainnya', 'Lainnya')], max_length=30)),
                ('tanggal', models.DateField()),
                ('biaya', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deskripsi', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=driver.models.foto_maintenance_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dilaporkan_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_maintenance', to=settings.AUTH_USER_MODEL)),
                ('kendaraan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log_maintenance', to='driver.kendaraan')),
            ],
            options={
                'verbose_name': 'Log Maintenance',
                'verbose_name_plural': 'Log Maintenance',
                'db_table': 'driver_log_maintenance',
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogBBM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('total_biaya', models.DecimalField(decimal_places=2, max_digits=12)),
                ('km_saat_isi', models.PositiveIntegerField(blank=True, help_text='KM odometer saat isi BBM', null=True)),
                ('keterangan', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=driver.models.foto_bbm_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_bbm', to=settings.AUTH_USER_MODEL)),
                ('kendaraan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log_bbm', to='driver.kendaraan')),
            ],
            options={
                'verbose_name': 'Log BBM',
                'verbose_name_plural': 'Log BBM',
                'db_table': 'driver_log_bbm',
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LaporanPerjalanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_laporan', models.DateField()),
                ('deskripsi', models.TextField(help_text='Deskripsi perjalanan dan aktivitas')),
                ('tujuan_tercapai', models.BooleanField(default=True)),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('log_perjalanan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laporan', to='driver.logperjalanan')),
            ],
            options={
                'verbose_name': 'Laporan Perjalanan',
                'verbose_name_plural': 'Laporan Perjalanan',
                'db_table': 'driver_laporan_perjalanan',
            },
        ),
        migrations.CreateModel(
            name='FotoLaporanPerjalanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to=driver.models.foto_laporan_perjalanan_path)),
                ('urutan', models.PositiveIntegerField(default=1, help_text='Urutan foto')),
                ('keterangan', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto', to='driver.laporanperjalanan')),
            ],
            options={
                'verbose_name': 'Foto Laporan Perjalanan',
                'verbose_name_plural': 'Foto Laporan Perjalanan',
                'db_table': 'driver_foto_laporan',
                'ordering': ['urutan', 'created_at'],
            },
        ),
    ]
